http://localhost:5000/api/product/

###

# REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "firstName": "Jerryson",
    "lastName": "Guillen",
    "email": "jerrysonguillen@gmail.com",
    "gender": "",
    "country": "",
    "region": "",
    "password": "password28"
}

###

# ACTIVATION
POST http://localhost:5000/api/auth/activation
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDaHJpc3RpYW4iLCJsYXN0TmFtZSI6IkxhY2FzdGUiLCJlbWFpbCI6ImNocmlzdGlhbjA5Mjg5M0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzEyMyIsImdlbmRlciI6Ik1hbGUiLCJjb3VudHJ5IjoiUGhpbGlwcGluZXMiLCJyZWdpb24iOiJOYXRpb25hbCBDYXBpdGFsIFJlZ2lvbiIsImlhdCI6MTYwODE2ODExNCwiZXhwIjoxNjA4NzcyOTE0fQ.kT2lA7BB8_os88UB4cyt0EvJnR_bfL9NLXJeLMz-quc"
}

###

# LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "christian092893@gmail.com",
    "password": "123123"
}

###

# FORGOT
PUT http://localhost:5000/api/auth/forgotpassword
Content-Type: application/json

{
    "email": "lacastetuts1@gmail.com"
}

###

# RESET
PUT http://localhost:5000/api/auth/resetpassword
Content-Type: application/json

{
    "resetPasswordLink": "",
    "newPassword": "321321"
}

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQzYTJlOTliZTEwZDE4NWM4YjIyOTIiLCJpYXQiOjE2MDc3MDU3MzgsImV4cCI6MTYwODMxMDUzOH0.ff84gTMFoX6DS0ag5veIU5KRf5knJ1s70nrHZ4DtKkI

###
POST http://localhost:5000/api/product/
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQzYTJlOTliZTEwZDE4NWM4YjIyOTIiLCJpYXQiOjE2MDc3NTg4MjYsImV4cCI6MTYwODM2MzYyNn0.Bhw27Wpr8v19Naap4aybPdo3tR1CV0pT2oNkr9x92JA

{
    "title":"sample1",
    "description":"potato chips",
    "category":["food","snack"],
    "images":["sample","sample2"],
    "price":30.00,
    "meetingPlace":"Quezon",
    "condition":"brand new"
}

###
DELETE http://localhost:5000/api/product/5fd3b5004f56d20f9c77c7ab
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQzYTJlOTliZTEwZDE4NWM4YjIyOTIiLCJpYXQiOjE2MDc3NTkwMDYsImV4cCI6MTYwODM2MzgwNn0.liUwgOHLI3R6fJdJ7Jl2sFopW-xvuhqgLcKj2-m6q4Q

#get product
###
http://localhost:5000/api/product/5fd3b5004f56d20f9c77c7ab

###
#TEST
GET http://localhost:5000/api/user/

###
#GET user
GET http://localhost:5000/api/user/getInfo
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRhYjJlNTQxMjJiODE1MzA4NTFlNzgiLCJpYXQiOjE2MDgxNjkzNTEsImV4cCI6MTYwODc3NDE1MX0.ZuHMwF7aOh6rDR-4b7hpeUlhJPCsekKkmz2p1EWdZLc


###
#GET user
POST  http://localhost:5000/api/user/update
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRhYjJlNTQxMjJiODE1MzA4NTFlNzgiLCJpYXQiOjE2MDgxNjkzNTEsImV4cCI6MTYwODc3NDE1MX0.ZuHMwF7aOh6rDR-4b7hpeUlhJPCsekKkmz2p1EWdZLc

{
    "firstName": "Christian",
    "lastName": "Lacaste",
    "gender": "Male",
    "country": "Thailand",
    "region": "Bangkok",
    "password": "password28"
}
