http://localhost:5000/api/auth

###

# REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "firstName": "Christian",
    "lastName": "Lacaste",
    "email": "lacastetuts1@gmail.com",
    "gender": "",
    "country": "",
    "region": "",
    "password": "password28"
}

###

# ACTIVATION
POST http://localhost:5000/api/auth/activation
Content-Type: application/json

{
    "token": ""
}

###

# LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "lacastetuts1@gmail.com",
    "password": "321321"
}

###

# FORGOT
PUT http://localhost:5000/api/auth/forgotpassword
Content-Type: application/json

{
    "email": "lacastetuts1@gmail.com"
}

###

# RESET
PUT http://localhost:5000/api/auth/resetpassword
Content-Type: application/json

{
    "resetPasswordLink": "",
    "newPassword": "321321"
}

